'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var TOKEN_VALIDATION_SUCCESS = exports.TOKEN_VALIDATION_SUCCESS = 'TOKEN_VALIDATION_SUCCESS';
var INSTANCE_CHANGE = exports.INSTANCE_CHANGE = 'INSTANCE_CHANGE';
var GET_APPS_SUCCESS = exports.GET_APPS_SUCCESS = 'GET_APPS_SUCCESS';
var GET_APPS_ERROR = exports.GET_APPS_ERROR = 'GET_APPS_ERROR';
var GET_PERMISSIONS_SUCESS = exports.GET_PERMISSIONS_SUCESS = 'GET_PERMISSIONS_SUCESS';
var CHANGE_APPNAME = exports.CHANGE_APPNAME = 'CHANGE_APPNAME';
var LOGIN = exports.LOGIN = 'LOGIN';
var LOGIN_SUCCESS = exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS';
var LOGIN_ERROR = exports.LOGIN_ERROR = 'LOGIN_ERROR';
var GET_HELP_COMPONENT_SUCCESS = exports.GET_HELP_COMPONENT_SUCCESS = 'GET_HELP_COMPONENT_SUCCESS';
var GET_HELP_COMPONENT_ERROR = exports.GET_HELP_COMPONENT_ERROR = 'GET_HELP_COMPONENT_ERROR';
var LOGOUT_USER = exports.LOGOUT_USER = 'LOGOUT_USER';
var IMPERSONATION_SUCESS = exports.IMPERSONATION_SUCESS = 'IMPERSONATION_SUCESS';
var END_IMPERSONATION = exports.END_IMPERSONATION = 'END_IMPERSONATION';