// <auto-generated />
namespace Nsu.Dal.AppCentral.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class deleteattr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteattr));
        
        string IMigrationMetadata.Id
        {
            get { return "201501301532062_deleteattr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
